### ISSUE TITLE
A question about the write up

### ISSUE THREAD

**Issue by Flyy-yu** [ymgve/ctf-writeups#1]
Hi ymgve:

how can you find out "../ is replaced before the path is accessed" ?

Thanks

**Comment by ymgve** [comment]
Assume you're talking about https://github.com/ymgve/ctf-writeups/tree/master/asis2017finals/web-mathilda - don't remember the exact steps I used, but I noticed that `path=../rooney` gave the same file as `path=rooney`. Also, `path=roo../ney` gave the same result, which meant there had to be some form of replacement going on.
